### ISSUE TITLE
CPU attempts counted twice

### ISSUE THREAD

**Issue by webmaster128** [PlasmaPower/nano-vanity#21]
The attemtps count is incremented [in check_soln](https://github.com/PlasmaPower/nano-vanity/blob/master/src/main.rs#L141) and [after check_soln](https://github.com/PlasmaPower/nano-vanity/blob/master/src/main.rs#L409), so I think it counts every attempt twice.

**Comment by PlasmaPower** [comment]
That's why I had the `- 1` in the gpu progress code! Let's just get rid of this: https://github.com/PlasmaPower/nano-vanity/blob/1d4414e970042213fb4067f8d4352d647a721a8f/src/main.rs#L140-L142

**Comment by webmaster128** [comment]
:) yes, check_soln is already doing too much suff

**Comment by webmaster128** [comment]
I [just verifierd](https://gist.github.com/webmaster128/1355b464943bdc56960dfd2c7811968f) that the average number of attemtps is 206 % of the expected value after 129 four char runs.
