### ISSUE TITLE
New NVIDIA OpenCL error

### ISSUE THREAD

**Issue by PlasmaPower** [PlasmaPower/nano-vanity#32]
I'm getting this when trying to compile any commit (I also tried 30eedd02251ffca) on my current system. I have opencl-nvidia 415.25-1 from the Arch Linux repositories.

```
Instruction does not dominate all uses!
  %getElem5841.16 = getelementptr [64 x i8] addrspace(5)* %125, i64 0, i64 16
  %1926 = bitcast i8 addrspace(5)* %getElem5841.16 to <4 x i32> addrspace(5)*
Broken module found, compilation terminated!
```

cc @webmaster128

**Comment by webmaster128** [comment]
No idea, sorry. Never came across that. Which NVIDIA driver works on which system is aktually a mystery to me. On GPUEater you cannot `apt upgrade` without breaking the driver and on a different Linux NVIDIA GPU server I also had trouble with some of the available drivers.

**Comment by PlasmaPower** [comment]
I've seen similar errors in the past with broken code, so I think this is probably a case of hidden undefined behavior.

**Comment by webmaster128** [comment]
I found [this](http://lists.llvm.org/pipermail/llvm-dev/2013-April/061235.html) which explains nicely what "Instruction does not dominate all uses!" means. However, it is probably hard to map those instructions in the error to .cl source code.

**Comment by PlasmaPower** [comment]
I guess I'll wait a while and see if newer drivers fix the problem, because it *shouldn't* give me an LLVM error, but I've seen LLVM errors before from broken OpenCL.

**Comment by webmaster128** [comment]
Duplicate of https://github.com/PlasmaPower/nano-vanity/issues/18

**Comment by PlasmaPower** [comment]
Good catch, thanks
