### ISSUE TITLE
--suffix "word" simple does not work: generates incorrect seeds

### ISSUE THREAD

**Issue by Eitz** [PlasmaPower/nano-vanity#36]
The software generates a key but it is not correct.

### Steps to reproduce:

1.  Use the following command to try to generate suffixes:
**Command:** `nano-vanity "1xx" --suffix "xx"  --gpu --simple-output --limit 0`
2. Wait for a key to show up (it would appear to work correctly)
**Example key/account:** `21FC40739D913D18CA48191311B63AA50A04C75AC8065DB3E60C5C244DC305A7 xrb_1xxhwfuxu55de4mm78sd393r4eccc4t5oekrbib3j3ptfefdayaocddewwxx`
3. Try to import this key in any wallet. The address there will be different from the above.
**Addrs for the key above:** `nano_1irrk8k5k5inprjgztx4c8cbiqgewjghn71ocajb1sdch59unqdtyg3js1q1`

**Comment by PlasmaPower** [comment]
You're thinking of seeds, not private keys. Use `--generate-seed` if you want a seed.

**Comment by Eitz** [comment]
Thanks for the quick feedback.
