### ISSUE TITLE
checkpoints maybe?

### ISSUE THREAD

**Issue by My1** [PlasmaPower/nano-vanity#37]
I am not sure if this just tries random numbers or there's some method (e.g. seeded RNG with counter) to this but if there it would really be nice to have some way to keep checkpoints so that on a crash you dont completely start over when generating something longer.

**Comment by PlasmaPower** [comment]
It's random, as you need your keys to be random. Also, due to keyspace this would have a negligible impact. Stopping and restarting the tool keeps going with the same efficiency.
