### ISSUE TITLE
failed to select a version for the requirement `rustc_version = "^0.1"

### ISSUE THREAD

**Issue by anarkrypto** [PlasmaPower/nano-vanity#39]
Installing nano-vanity v0.4.10 (/home/anarkrypto/nano/nano-vanity)
    Updating crates.io index
error: failed to compile `nano-vanity v0.4.10 (/home/anarkrypto/nano/nano-vanity)`, intermediate artifacts can be found at `/home/anarkrypto/nano/nano-vanity/target`

Caused by:
  failed to select a version for the requirement `rustc_version = "^0.1"`
  candidate versions found which didn't match: 0.3.3, 0.3.2, 0.3.1, ...
  location searched: crates.io index
  required by package `ocl-core v0.10.0`
      ... which is depended on by `ocl v0.19.0`
      ... which is depended on by `nano-vanity v0.4.10 (/home/anarkrypto/nano/nano-vanity)`

**Comment by PlasmaPower** [comment]
Seems to be caused by https://github.com/cogciprocate/ocl/issues/203 . If anyone has any recommendations for alternatives let me know.
