### ISSUE TITLE
Windows build (release)

### ISSUE THREAD

**Issue by AugustoResende** [PlasmaPower/nano-vanity#4]
I am not able to compile the program on windows. You can make a release please?

**Comment by PlasmaPower** [comment]
What error are you getting?

**Comment by AugustoResende** [comment]
https://i.imgur.com/6VwJV46.png

**Comment by PlasmaPower** [comment]
It looks like Rust can't find OpenCL on Windows. I've made some changes to try to help Rust find OpenCL, so try again with the latest version.

**Comment by PlasmaPower** [comment]
Also, I don't think a Windows release is feasible. Most likely, I'd have to create 3 releases: NVIDIA, AMD, and Intel. I don't have devices with all of those GPUs.

**Comment by PlasmaPower** [comment]
This problem was fixed by installing the Nvidia CUDA toolkit, restarting, then removing the Rust cache folder `target`.
