### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by adrianegraphene** [PlasmaPower/nano-vanity#40]
Hello, 
I thought I'd leave this here in case it helps narrow down the source of the issue that seems to be reference in this [previous issue.](https://github.com/PlasmaPower/nano-vanity/issues/18)

output of `nvcc -V` on Windows showing that cuda was installed. 

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Mon_May__3_19:41:42_Pacific_Daylight_Time_2021
> Cuda compilation tools, release 11.3, V11.3.109
> Build cuda_11.3.r11.3/compiler.29920130_0

C++ was installed through visual studio community 2019.

GPU: Nvidia GeForce GTX 1650 Super
CPU: AMD Ryzen 5 3600

```
C:\Users\me\Documents\GitHub\nano-vanity> nano-vanity -g .karmaca1
Estimated attempts needed: 1099511627776
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 

###################### OPENCL PROGRAM BUILD DEBUG OUTPUT ######################

<kernel>:292:25: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
          blake2b_compress( S, S->buf ); // Compress
                               ^~~~~~
<kernel>:198:70: note: passing argument to parameter 'block' here
static int blake2b_compress( blake2b_state *S, __private const uchar block[BLAKE2B_BLOCKBYTES] )
                                                                     ^
<kernel>:317:23: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
        blake2b_compress( S, S->buf );
                             ^~~~~~
<kernel>:198:70: note: passing argument to parameter 'block' here
static int blake2b_compress( blake2b_state *S, __private const uchar block[BLAKE2B_BLOCKBYTES] )
                                                                     ^
<kernel>:331:24: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
  blake2b_compress( S, S->buf );
                       ^~~~~~
<kernel>:198:70: note: passing argument to parameter 'block' here
static int blake2b_compress( blake2b_state *S, __private const uchar block[BLAKE2B_BLOCKBYTES] )
                                                                     ^

###############################################################################

', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\nano-vanity-0.4.10\src\main.rs:404:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Some googling on the first issue brought me [to this page.](https://stackoverflow.com/questions/14651558/opencl-pass-by-reference-different-addres-space), but I am unable to diagnose further. 

Wish I could be of more help! Also wish I could make this amazing tool work for this GPU! Thanks.

**Comment by CaptainCaptcha** [comment]
I have the exact same problem. My GPU is RTX 3080 Ti

**Comment by thooton** [comment]
https://github.com/openwall/john/issues/4667#issuecomment-821221733 details the issue.

Here's a copy of `src/opencl/blake2b.cl` that seems to fix the issue (at least for myself). It should just be a drop-in replacement, then you can follow the instructions to install from source in the readme

[blake2b.zip](https://github.com/PlasmaPower/nano-vanity/files/6730597/blake2b.zip)

**Comment by adrianegraphene** [comment]
No longer have my Nvidia GPU or I would try the above solution. Would be useful to know if that helps resolves the problem for others, then I guess we could close this with that solution.

**Comment by CaptainCaptcha** [comment]
@thooton I can confirm that it works! I'm getting ~28.000.000 with my RTX 3080 Ti GPU and Ryzen 9 5900x (I only give 4 threads of it to the script). Thank you for the fix dude :)

**Comment by adrianegraphene** [comment]
Awesome, let's consider this closed with this solution. I'll try it on my next Nvidia GPU. Thanks @thooton
