### ISSUE TITLE
Seed doesn't match generated wallet

### ISSUE THREAD

**Issue by WilliamsPaulM** [PlasmaPower/nano-vanity#42]
I generated an address:
`nano_1nicknamea58s7t9kxdaqndgb6udb3kge7peys13rjqqroxnsjcaxmhmjb8a`

However, when I add the Private Key to Natrium I'm getting a different address:
`nano_3hagfztpzj1sofogh6cf9d5ywxybsx8q6mskkhqz6p5b4s3swwc4wnj6q4dg`

**Comment by PlasmaPower** [comment]
Use `--generate-seed`, the default is a private key which is different (and which I don't think Natrium supports).
