### ISSUE TITLE
installing without opencl?

### ISSUE THREAD

**Issue by Minecon724** [PlasmaPower/nano-vanity#45]
opencl is required even when not using the features gpu argument

heres the error: https://pastebin.com/d8iN1bVc

**Comment by deleterium** [comment]
@Minecon724  Currently it is set to default compiling using gpu. So to deactivate you need to
1. Open file `Cargo.toml`
2. Delete line 13: `default = ["gpu"]`
3. Compile the program `cargo build --release`
4. Use the program that will be available at `target/release/nano-vanity`
