### ISSUE TITLE
Address does not appear when importing into nanowallet

### ISSUE THREAD

**Issue by AvelinoMorganti** [PlasmaPower/nano-vanity#8]
I generated an address with this program, but when importing my seed into nanowallet the corresponding address does not appear. Could you print the index in a future version?

I am trying to loop through all the addresses to find the generated address: /

**Comment by PlasmaPower** [comment]
It's always index 0. Does it not work?

**Comment by AvelinoMorganti** [comment]
I just looked at the code. I must have confused the seed with the private key. My mistake.

**Comment by PlasmaPower** [comment]
There's a `--generate-seed` option. Maybe it should be default?

**Comment by AvelinoMorganti** [comment]
Yes. Or print both the private key and the seed. I do not know...

I think the private key is only possible by placing it in the wallet desktop files.

People will even use it is the seed.

**Comment by PlasmaPower** [comment]
Generating the seed is a bit slower than generating the private key, so I used the latter as the default. I'll run some tests to see what the performance difference is, and if I should default to `--generate-seed`.

**Comment by AvelinoMorganti** [comment]
Ah, now I understand why you chose this.

Sorry to have opened an issue. My mistake.

**Comment by PlasmaPower** [comment]
No problem :). You're not the first user to be confused by this.

**Comment by PlasmaPower** [comment]
I'll do more comprehensive tests later, but right now it looks like it has a 10% (maybe a bit less) performance penalty. For now I'll leave private key generation as the default.

**Comment by caseyscarborough** [comment]
@PlasmaPower if we have the generated private key, how can we go about adding it to the desktop wallet? I've entered it into the "Import adhoc key" field but clicking the button doesn't seem to do anything other than clear the text field.

**Comment by PlasmaPower** [comment]
It's really odd but the wallet doesn't display adhoc keys unless they have a nonzero balance. I think it's to discourage them because they aren't backed up in the backup folder automatically.

**Comment by caseyscarborough** [comment]
Ahh, thanks! It shows if I call the `account_list` RPC action. I believe there is no way to get the seed from the private key, correct?

**Comment by PlasmaPower** [comment]
No, that's like getting a private key from a public key. A seed for a given private key may not even exist.

**Comment by caseyscarborough** [comment]
I see, makes sense. Thanks again for the help.

**Comment by LivanSteam** [comment]
neponimat
